language: php

php:
  - 7.4

before_install:
  - cp .env.example .env

install:
  - composer self-update
  - composer install --no-interaction

script:
  - ./bin/phpunit

addons:
  ssh_known_hosts: 77.120.107.185:20022
