language: php

php:
  - 7.4

before_install:
  - cp .env.example .env

install:
  - composer self-update
  - composer install --no-interaction

script:
  - ./bin/phpunit

before_deploy:
  - echo "$MY_ID_RSA" > ~/id_rsa.pub

deploy:
  provider: script
  script: ./vendor/bin/dep deploy prod -vvv
  skip_cleanup: true
  on:
    branch: main